module.exports = {
  USERS: 'users',
  USER_FEATURES : 'user_features',
  USER_FEATURES_RELATION: 'user_features_users_relation',
  USER_ROLES: 'user_roles',
  USER_STATUS: 'user_statuses',
  REVIEWS: 'reviews',
  CATEGORY: 'categories', 
  COMMENTS: 'comments',
  LIKES: 'likes',
  MOVIES: 'movies',
  MOVIES_CATEGORIES_RELATION:'movies_categories_relation',
  FILMAKING_MEMBERS: 'filmaking_members',
  FILMAKING_MEMBERS_ROLES: 'filmaking_members_roles',
}